/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_jhkoder_rest_system_ProcessAccessorWindows */

#ifndef _Included_github_jhkoder_rest_system_ProcessAccessorWindows
#define _Included_github_jhkoder_rest_system_ProcessAccessorWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_jhkoder_rest_system_ProcessAccessorWindows
 * Method:    isProcessRunning
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_github_jhkoder_rest_system_ProcessAccessorWindows_isProcessRunning
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     github_jhkoder_rest_system_ProcessAccessorWindows
 * Method:    getTargetProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lgithub/jhkoder/rest/system/ProcessResourceResponse;
 */
JNIEXPORT jobject JNICALL Java_github_jhkoder_rest_system_ProcessAccessorWindows_getTargetProfile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
