/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_jhkoder_rest_system_ProcessAccessorLinux */

#ifndef _Included_github_jhkoder_rest_system_ProcessAccessorLinux
#define _Included_github_jhkoder_rest_system_ProcessAccessorLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_jhkoder_rest_system_ProcessAccessorLinux
 * Method:    isProcessRunning
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_github_jhkoder_rest_system_ProcessAccessorLinux_isProcessRunning
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     github_jhkoder_rest_system_ProcessAccessorLinux
 * Method:    getTargetProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_jhkoder_rest_system_ProcessAccessorLinux_getTargetProfile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
